### ISSUE TITLE
Works at university of cape town

### ISSUE THREAD

**Issue by riazarbi** [oleks/eduroam-wpa_supplicant#11]
Please add to documented university list. 

I did not use a hashed password, cleartext works fine.

**Comment by oleks** [comment]
Cool!

Password hashing only "protects" your password while stale on disk. So if you have some bot crawling around locally, it won't directly be able to peak at your password. But the hashing algorithm employed is too weak to be of _any_ practical value. Perhaps I should remove that part of the guide entirely.
