### ISSUE TITLE
Works at University Koblenz-Landau

### ISSUE THREAD

**Issue by patrick-nits** [oleks/eduroam-wpa_supplicant#15]
The config works at the University Koblenz-Landau (March 13 2018).

However, for Raspbian Stretch you need to add the following line(s)

`ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=root`
`country=<2 Letter Country Code>`

**Comment by oleks** [comment]
Maybe it's about time to have a Google Maps-image in the README.md, with pins :-)

> `ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=root`

Isn't this only necessary if you are using `wpa_cli`? Not that it's a bad idea, just to clarify.

> `country=<2 Letter Country Code>`

Which country are you supposed to denote? Your home country, or where you are currently at?

**Comment by patrick-nits** [comment]
Regarding
> ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=root <

This only relevant for Raspbian (Stretch), as it indeed uses `wpa_cli`. 
Same goes for:
> country=2 Letter Country Code <

I´m not sure which country code they require. Most likely the code of the country you are currently at.
