### ISSUE TITLE
Use anonymous_identity

### ISSUE THREAD

**Issue by michael-dev** [oleks/eduroam-wpa_supplicant#7]
I'm wondering whether anonymous_identity should be added so that when roaming the personal identity is only revealed to the home university?

**Comment by oleks** [comment]
I'm not sure this would work across the board. I know that many universities suggest leaving the `anonymous_identiy` _blank_. Whether leaving it blank is sometimes important, is unclear to me. You could argue that a university that _demands_ you leave it blank, is not worth connecting to :-)

For instance,

- [University of Oslo](http://www.uio.no/english/services/it/network/wireless/help/eduroam/android/) - "_should_ be left blank" (emphasis added)
- [University of Californa Santa Cruz](https://its.ucsc.edu/wireless/eduroam-manual-config.html) - "leave blank"
- [University of Minnesota](https://it.umn.edu/wifi-how-connect-eduroam) - "not needed, leave blank"

At the same time, some universities do suggest setting this to some value:

- [University of Cambridge](https://help.uis.cam.ac.uk/devices-networks-printing/mobile-devices/android/eduroam-android) - "@cam.ac.uk (i.e. without the leading CRSid)"
- [University of Oxford](https://help.it.ox.ac.uk/network/wireless/services/eduroam/android/index) - "Add in your Remote Access account username again followed by @ox.ac.uk e.g. abcd0123@ox.ac.uk"

[UC Davis](http://ithelp.physics.ucdavis.edu/kb/linux-wireless-connection-issues-eduroam-and-moobilenetx) is really exotic on this one - "Leave blank unless you're having trouble connecting. Then, for Eduroam try: anonymous@ucdavis.edu or @ucdavis.edu. You can also try anonymous but this may have no effect (?)."

**Comment by michael-dev** [comment]
Skipping the anonymous_identity setting will have wpa_supplicant default to the identity configured.
Using an empty outer identity might only work when at home university as it will not provide any hint to eduroam which university the request should be sent to.

Maybe anonymous_identity could be added to the default config with a decent warning that the user might need to remove it?
